### ISSUE TITLE
mech-and-cow not properly formatted

### ISSUE THREAD

**Issue by echenran** [piuccio/cowsay#8]
The [mech-and-cow.cow file](https://raw.githubusercontent.com/piuccio/cowsay/master/cows/mech-and-cow.cow) is not properly formatted and generates errors when used as `cowsay -f mech-and-cow something`

**Comment by piuccio** [comment]
```
:~ piuccio$ cowsay -f mech-and-cow "I can't replicate"
 ___________________
< I can't replicate >
 -------------------
                                   ,-----.
                                   |     |
                                ,--|     |-.
                         __,----|  |     | |
                       ,;::     |  `_____' |
                       `._______|    i^i   |
                                `----| |---'| .
                           ,-------._| |== ||//
                           |       |_|P`.  /'/
                           `-------' 'Y Y/'/'
                                     .==\ /_\
   ^__^                             /   /'|  `i
   (oo)\_______                   /'   /  |   |
   (__)\       )\/\             /'    /   |   `i
       ||----w |           ___,;`----'.___L_,-'`\__
       ||     ||          i_____;----\.____i""\____\

```

**Comment by timw** [comment]
For posterity...

This is a problem with the original cowsay - if you're using the Perl based cowsay (e.g from Homebrew on Mac) it will fail on mech-and-cow (the file in the JS port here is identical to that in the original cowsay distro).

The root cause is that this cow was never finished - it's missing the script bits to define the cow and escape all the ASCII art (e.g. `$the_cow = <<EOC` etc.) as well as the `$tongue/$eye/$thought` inserts. In the original cowsay distro, this isn't even a `.cow` file - I wonder if Tony got sick of telebears and graduated prior to getting round to it...

For the obsessives among us, here's a working mech-and-cow (rename to mech-and-cow.cow in your cows directory).
[mech-and-cow.txt](https://github.com/piuccio/cowsay/files/387943/mech-and-cow.txt)
